import { Router, type IRouter } from "express";
import healthRouter from "../features/health/routes";
import authRouter from "../features/auth/routes";
import amRouter from "../features/am/routes";
import importRouter from "../features/import/routes";
import performanceRouter from "../features/performance/routes";
import funnelRouter from "../features/funnel/routes";
import activityRouter from "../features/activity/routes";
import telegramRouter from "../features/telegram/routes";
import settingsRouter from "../features/settings/routes";
import gSheetsRouter from "../features/gsheets/routes";
import gDriveRouter from "../features/gdrive/routes";
import corporateRouter from "../features/corporate/routes";
import publicAmRouter from "../features/am/publicRoutes";
import publicPerformanceRouter from "../features/performance/publicRoutes";
import publicFunnelRouter from "../features/funnel/publicRoutes";
import publicActivityRouter from "../features/activity/publicRoutes";
import publicSettingsRouter from "../features/settings/publicRoutes";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(amRouter);
router.use(importRouter);
router.use(performanceRouter);
router.use(funnelRouter);
router.use(activityRouter);
router.use(telegramRouter);
router.use(settingsRouter);
router.use(gSheetsRouter);
router.use(gDriveRouter);
router.use(corporateRouter);
router.use(publicAmRouter);
router.use(publicPerformanceRouter);
router.use(publicFunnelRouter);
router.use(publicActivityRouter);
router.use(publicSettingsRouter);

export default router;
